### ISSUE TITLE
Reproducing Baselines

### ISSUE THREAD

**Issue by jonathanbrady88** [JohannesAck/OfflineRLStructuredNonstationarity#1]
Thank you for sharing the code of your inspirational research!! I’m interested in reproducing the experiments, and I was wondering if it would be possible to share the baselines or any additional details that could help with reproducing.

**Comment by JohannesAck** [comment]
Hi @jonathanbrady88,
Thanks a lot for checking out the paper! 
I did some refactoring and added additional documentation for the code before publishing this repo.
Thus the baselines are sightly incompatible and unfortunately I won't have the time to incorporate them in this repo in the near future.

However, if you'd like I can send you the slightly messy baseline code privately by email. 
Feel free to send me an email saying so to the address from the paper!
